config/routes.rb
Rails.application.routes.draw do
  root to: "parks#index"
  resources :parks

  constraints format: :json do
    namespace :api do
      namespace :v1 do
        resources :parks, param: :name
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  def overlap?
    Park.where(floor: self.floor, number: self.number).exists?
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/parks_controller.rb
class Api::V1::ParksController < Api::V1::ApplicationController
  before_action :set_park, only: [:show, :update, :destroy]

  # GET /parks
  # GET /parks.json
  def index
    @parks = Park.all

    render json: @parks
  end

  # GET /parks/1
  # GET /parks/1.json
  def show
    if @park
      render json: { rtn: 'success' }
    else
      render json: { rtn: 'failed' }
    end
  end

  # POST /parks
  # POST /parks.json
  def create
    @park = Park.new(park_params)

    if @park.invalid?
      render json: { rtn: 'failed: name exists'  }
    elsif not @park.overlap? and @park.save
      render json: { rtn: 'success' }
    else
      render json: { rtn: 'failed: position exists' }
    end
  end

  # PATCH/PUT /parks/1
  # PATCH/PUT /parks/1.json
  def update
    if @park.update(park_params)
      render json: @park, status: :ok, location: @park
    else
      render json: @park.errors, status: :unprocessable_entity
    end
  end

  # DELETE /parks/1
  # DELETE /parks/1.json
  def destroy
    if @park and @park.destroy
      render json: { rtn: 'success' }
    else
      render json: { rtn: 'failed' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_park
      @park = Park.find_by_name(params[:name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def park_params
      params.permit(:name, :floor, :number, :phone)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :set_park, only: [:show, :edit, :update, :destroy]

  # GET /parks
  # GET /parks.json
  def index
    @parks = Park.all
  end

  # GET /parks/1
  # GET /parks/1.json
  def show
  end

  # GET /parks/new
  def new
    @park = Park.new
  end

  # GET /parks/1/edit
  def edit
  end

  # POST /parks
  # POST /parks.json
  def create
    @park = Park.new(park_params)

    respond_to do |format|
      if @park.save
        format.html { redirect_to @park, notice: 'Park was successfully created.' }
        format.json { render :show, status: :created, location: @park }
      else
        format.html { render :new }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parks/1
  # PATCH/PUT /parks/1.json
  def update
    respond_to do |format|
      if @park.update(park_params)
        format.html { redirect_to @park, notice: 'Park was successfully updated.' }
        format.json { render :show, status: :ok, location: @park }
      else
        format.html { render :edit }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parks/1
  # DELETE /parks/1.json
  def destroy
    @park.destroy
    respond_to do |format|
      format.html { redirect_to parks_url, notice: 'Park was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_park
      @park = Park.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def park_params
      params.require(:park).permit(:name, :floor, :number, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parks/_form.html.erb
<%= form_for(park) do |f| %>
  <% if park.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(park.errors.count, "error") %> prohibited this park from being saved:</h2>

      <ul>
      <% park.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :floor %>
    <%= f.number_field :floor %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parks/edit.html.erb
<h1>Editing Park</h1>

<%= render 'form', park: @park %>

<%= link_to 'Show', @park %> |
<%= link_to 'Back', parks_path %>

app/views/parks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Floor</th>
      <th>Number</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parks.each do |park| %>
      <tr>
        <td><%= park.name %></td>
        <td><%= park.floor %></td>
        <td><%= park.number %></td>
        <td><%= park.phone %></td>
        <td><%= link_to 'Show', park %></td>
        <td><%= link_to 'Edit', edit_park_path(park) %></td>
        <td><%= link_to 'Destroy', park, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Park', new_park_path %>

app/views/parks/new.html.erb
<h1>New Park</h1>

<%= render 'form', park: @park %>

<%= link_to 'Back', parks_path %>

app/views/parks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @park.name %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @park.floor %>
</p>

<p>
  <strong>Number:</strong>
  <%= @park.number %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @park.phone %>
</p>

<%= link_to 'Edit', edit_park_path(@park) %> |
<%= link_to 'Back', parks_path %>